### ISSUE TITLE
在win上自动生成的时候对于一些字符直接转义了

### ISSUE THREAD

**Issue by wozhizhizhi** [flutter-dev/asset_generator#2]
/// ![](http://127.0.0.1:2227/images/2.0x\readfooter1.png)
  static final String images20x\readfooter1Png = 'images/2.0x\readfooter1.png';
  /// ![](http://127.0.0.1:2227/images/2.0x\task_bg.png)
  static final String images20x\taskBgPng = 'images/2.0x\task_bg.png';
  /// ![](http://127.0.0.1:2227/images/2.0x\task_btn_return.png)
  static final String images20x\taskBtnReturnPng = 'images/2.0x\task_btn_return.png';
  /// ![](http://127.0.0.1:2227/images/2.0x\task_icon_reading.png)
  static final String images20x\taskIconReadingPng = 'images/2.0x\task_icon_reading.png';

**Comment by debuggerx01** [comment]
@wozhizhizhi Thx，改过了，应该可用了。windows的路径问题是真的烦，已经不知道是第几次被坑了。。

**Comment by wozhizhizhi** [comment]
谢谢作者及时修复！，win是挺坑的我也被坑了好多次--！
